# Generated by Django 5.0 on 2023-12-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='estate',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('GBP', 'Gbp'), ('UZS', 'Uzs')], default='USD', max_length=3),
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
