# Generated by Django 5.0 on 2023-12-20 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_estate_market_value_alter_estate_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='license',
            field=models.FileField(default=56, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agents',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Licenses',
        ),
    ]
