# Generated by Django 5.0 on 2023-12-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_agents_license_alter_agents_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='license',
            field=models.FileField(default='No License', upload_to=''),
        ),
    ]
