# Generated by Django 5.0 on 2024-01-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_estate_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='api.image'),
        ),
    ]
