# Generated by Django 5.0 on 2024-01-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_estate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='image',
            field=models.ManyToManyField(blank=True, to='api.image'),
        ),
    ]
