# Generated by Django 5.0 on 2024-01-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='image',
        ),
        migrations.AddField(
            model_name='estate',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
    ]
